### ISSUE TITLE
Design upgrade for Search Bar on elements page

### ISSUE THREAD

**Issue by sarthakkundra** [AasthaGithub/Customizable_Portfolio#32]
The design of search bar on elements page was just a placeholder for the first review. We need to upgrade it to match the theme of the page. Feel free to explore your creativity with it's design just make sure not to break the functionality.

 Attach a picture of your changes or preferably a video of it's working state with your changes in the PR .

**Comment by akrishna0** [comment]
Okay I will fix it Today

**Comment by akrishna0** [comment]
I have worked on it please review  and close this issue if it is resolved
