### ISSUE TITLE
Complete the Usage part in the Docs

### ISSUE THREAD

**Issue by sarthakkundra** [AasthaGithub/Customizable_Portfolio#49]
The Usage part of the docs should have the following points at least

1. How to explore and search for different elements.
2. How to view and download their code.
3. How to contribute elements.

Attach GIFs of all the actions so that it's easier for the person to understand just by looking at the video.

**Comment by Vidit-jindal** [comment]
I would like to take this issue.

**Comment by sarthakkundra** [comment]
@Vidit-jindal Assigned
