### ISSUE TITLE
Update the Screenshot in Readme

### ISSUE THREAD

**Issue by akrishna0** [AasthaGithub/Customizable_Portfolio#57]
The Screenshot in the Readme is not updated.

**Comment by sarthakkundra** [comment]
Please specify what all is not updated clearly like what is present at the moment and what changes do you propose.

**Comment by akrishna0** [comment]
Yeah it was in the Readme file of the root directory in the About The Project section .
And it has been taken care of by @Vidit-jindal

**Comment by Vidit-jindal** [comment]
I think screenshot is updated now @akrishna0
