### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by sarthakkundra** [AasthaGithub/Customizable_Portfolio#64]
Now that we're about to release our project, it'd be good to have an issue template in case someone wants to report an issue. This will help us get all the information about the issue so that we can work on it quickly. The template shoul **at least** include these headings. Feel free to add more if you feel so.

- [ ] Type of issue

- [ ] Steps to recreate 

- [ ] Screenshots (if any)

- [ ] Run-time environment

**Comment by AasthaGithub** [comment]
Bug, Feature Request & basic custom Issue templates created
