### ISSUE TITLE
CheckBox State Update

### ISSUE THREAD

**Issue by AasthaGithub** [AasthaGithub/Customizable_Portfolio#79]
**Type of issue/enquiry**
- CheckBox State Update either by Individual/global state update & maintenance

**Description**
- Clear All CheckBoxes of individual elements after "DownloadAll" button is clicked <br>
so as to avoid manual unchecking if user wants to use it again.

 **Other Specifications**
- Steps to recreate : Go to Elements Page -> Check few elements -> Click Merge Button -> Click Download All Button <br>

Note: Although the selected _set & merged_strings gets cleared but checkboxes still remain marked

- Hardware/software specification : Any

**Comment by stefanuslim** [comment]
Hi, can I work on this?

**Comment by AasthaGithub** [comment]
Sure, go ahead @stefanuslim

**Comment by AasthaGithub** [comment]
Solved by https://github.com/AasthaGithub/Customizable_Portfolio/pull/81
